# Generated by Django 5.2.6 on 2025-09-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile',
            new_name='phone',
        ),
    ]
