# Generated by Django 5.2.6 on 2025-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_remove_room_capacity_remove_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to='room_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
