# Generated by Django 5.2.6 on 2025-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_bill_paid_contact_user_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
